/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/Joke": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Joke.id"];
          createdAt?: parameters["rowFilter.Joke.createdAt"];
          updatedAt?: parameters["rowFilter.Joke.updatedAt"];
          name?: parameters["rowFilter.Joke.name"];
          content?: parameters["rowFilter.Joke.content"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["Joke"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** Joke */
          Joke?: definitions["Joke"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Joke.id"];
          createdAt?: parameters["rowFilter.Joke.createdAt"];
          updatedAt?: parameters["rowFilter.Joke.updatedAt"];
          name?: parameters["rowFilter.Joke.name"];
          content?: parameters["rowFilter.Joke.content"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Joke.id"];
          createdAt?: parameters["rowFilter.Joke.createdAt"];
          updatedAt?: parameters["rowFilter.Joke.updatedAt"];
          name?: parameters["rowFilter.Joke.name"];
          content?: parameters["rowFilter.Joke.content"];
        };
        body: {
          /** Joke */
          Joke?: definitions["Joke"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  Joke: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    createdAt: string;
    updatedAt: string;
    name: string;
    content: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** Joke */
  "body.Joke": definitions["Joke"];
  "rowFilter.Joke.id": string;
  "rowFilter.Joke.createdAt": string;
  "rowFilter.Joke.updatedAt": string;
  "rowFilter.Joke.name": string;
  "rowFilter.Joke.content": string;
}

export interface operations {}

export interface external {}
